# Generated by Django 4.2 on 2023-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=64)),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
                ('tag', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
