# Generated by Django 4.2 on 2023-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=5000)),
                ('photo_1300', models.CharField(max_length=5000)),
                ('photo1_600', models.CharField(max_length=5000)),
                ('photo2_600', models.CharField(max_length=5000)),
            ],
        ),
    ]
